using UnityEngine;
using System.Collections.Generic;

public class BattlePhaseManager : MonoBehaviour
{
	public BattlePhase Phase;
	public BattlePhase currentPhase;
	public BattlePhase prevPhase;
	public GameObject currentCreature;
	public string currentCardID;
	public bool newTurn;
	public GameObject tweenToP1Setup;
	public GameObject tweenToP1Setup_LabelOnly;
	public GameObject tweenToP1SetupAction;
	public GameObject tweenToP1SetupActionRareCard;
	public GameObject tweenToP1SetupActionSpell;
	public GameObject tweenToP1FloopAction;
	public GameObject tweenToP1FloopActionHero;
	public GameObject tweenToP1LeaderAbility;
	public GameObject tweenToP1LeaderAbilityAction;
	public GameObject tweenToP1LeaderAbilityActionHero;
	public GameObject tweenToP1SpellCreature;
	public GameObject tweenToP1SpellHero;
	public GameObject tweenToP2Setup;
	public GameObject tweenToP2Setup_LabelOnly;
	public GameObject tweenToP2SetupAction;
	public GameObject tweenToP2SetupActionRareCard;
	public GameObject tweenToP2SetupActionSpell;
	public GameObject tweenToP2FloopAction;
	public GameObject tweenToP2FloopActionHero;
	public GameObject tweenToP2LeaderAbility;
	public GameObject tweenToP2LeaderAbilityAction;
	public GameObject tweenToP2LeaderAbilityActionHero;
	public GameObject tweenToP2SpellCreature;
	public GameObject tweenToP2SpellHero;
	public GameObject tweenToP1SetupLanePlyr;
	public GameObject tweenToP1SetupLaneOpp;
	public GameObject tweenToP1Battle;
	public GameObject tweenToLootAfterP1Battle;
	public GameObject tweenToP2Battle;
	public GameObject tweenToLootAfterP2Battle;
	public GameObject tweenToResultP1Defeated;
	public GameObject tweenToResultP2Defeated;
	public GameObject tweenToResultP1Win;
	public GameObject tweenToResultP1WinPanel;
	public GameObject tweenToResultP1Lose;
	public GameObject tweenToResultP1LosePanel;
	public GameObject tweenToResultP1Dweeb;
	public GameObject tweenToResultP1MPWin;
	public GameObject tweenToResultP1MPWinPanel;
	public GameObject tweenToResultP1MPLose;
	public GameObject tweenToResultP1MPLosePanel;
	public GameObject tweenToOutOfCard;
	public GameObject tweenToReshuffle;
	public GameObject tweenToP2Win;
	public GameObject tweenToP2Dweeb;
	public GameObject tweenToGameOver;
	public List<string> alreadySummonedCard;
	public GameObject winnerResult;
	public GameObject loserResult;
	public GameObject tweenToPosgameWin;
	public GameObject tweenToPosgameLose;
	public GameObject tweenToBannerP1;
	public GameObject tweenToBannerP2;
	public GameObject tweenToBattleBannerP1;
	public GameObject tweenToBattleBannerP2;
}
